<?php
$base_dir   = __DIR__ . '/Base';
$static_url = '/assets';

ob_start();
include "$base_dir/navbar2.php";
$navlink_content = ob_get_clean();
$page  = 'nav2';
$fpage = 'foot';

ob_start();
?>

<!-- ============================ Page Title ================================== -->
<div class="image-cover page-title" style="background:#002446 url(<?php echo $static_url; ?>/img/new-banner.jpg) no-repeat center center / cover;" data-overlay="7">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12">
                <h2 class="ipt-title" style="color:#fff;">Legal Disclaimer</h2>
                <span class="ipn-subtitle" style="color:rgba(255,255,255,.75);">
                    Last Updated: February 28, 2026 &nbsp;·&nbsp; Wynston.ca
                </span>
            </div>
        </div>
    </div>
</div>
<!-- ============================ Page Title End ================================== -->

<!-- ============================ Disclaimer Body ================================== -->
<section class="pt-0">
<div class="container">
<div class="row">

    <!-- ── Sidebar ───────────────────────────────────────────────────────── -->
    <div class="col-lg-3 col-md-12 d-none d-lg-block">
        <div class="terms-toc">
            <div class="terms-toc-title">On This Page</div>
            <ul class="terms-toc-list">
                <li><a href="#d-mls">MLS® Data & REBGV Attribution</a></li>
                <li><a href="#d-gap">The Invisibility Gap</a></li>
                <li><a href="#d-nopurchase">No Purchase or Deposit</a></li>
                <li><a href="#d-vow">VOW Registration</a></li>
                <li><a href="#d-redma">REDMA Notice for Developers</a></li>
                <li><a href="#d-agency">No Agency Created</a></li>
                <li><a href="#d-prof">Professional Disclosure</a></li>
            </ul>

            <div style="margin-top:24px;padding-top:16px;border-top:1px solid #f0ece6;">
                <div class="terms-toc-title">Related Documents</div>
                <ul class="terms-toc-list">
                    <li><a href="terms.php">Terms of Service</a></li>
                    <li><a href="privacy.php">Privacy Policy</a></li>
                </ul>
            </div>
        </div>
    </div>

    <!-- ── Main content ──────────────────────────────────────────────────── -->
    <div class="col-lg-9 col-md-12">
    <div class="terms-body">

        <div class="terms-preamble">
            This page contains important legal notices, data attributions, and disclosures that apply to all users of the Wynston Platform — including buyers, sellers, and real estate developers. Please read each section carefully. Use of the Platform constitutes acceptance of these disclosures.
        </div>

        <!-- ── MLS® Data ── -->
        <div class="terms-section" id="d-mls">
            <div class="disc-badge disc-badge-blue">MLS® Data Attribution</div>
            <h2 class="terms-h2">MLS® Data & REBGV Attribution</h2>

            <div class="disc-rebgv-block">
                <div class="disc-rebgv-logo-area">
                    <div class="disc-rebgv-seal">MLS®</div>
                </div>
                <div class="disc-rebgv-text">
                    The data relating to real estate on this website comes in part from the MLS® Reciprocity program of the Real Estate Board of Greater Vancouver. Real estate listings held by participating real estate firms are marked with the MLS® logo and detailed information about the listing includes the name of the listing agent. This representation is based in whole or part on data generated by the Real Estate Board of Greater Vancouver which assumes no responsibility for its accuracy. The materials contained on this page may not be reproduced without the express written consent of the Real Estate Board of Greater Vancouver.
                </div>
            </div>

            <ul class="terms-list" style="margin-top:20px;">
                <li>Active listing data is sourced via a licensed MLS® data feed and is updated approximately every <strong>two (2) hours</strong>. There may be a delay between when a listing is entered into the MLS® System and when it appears on this Platform.</li>
                <li>MLS® data is deemed reliable but <strong>not guaranteed accurate</strong> by the Real Estate Board of Greater Vancouver or its member brokerages. All measurements, square footages, and property details should be independently verified.</li>
                <li>All active listing data displayed on this Platform is provided under license to <strong>Tam Nguyen, REALTOR®</strong>, with Royal Pacific Realty Corporation.</li>
                <li>The trademarks MLS®, Multiple Listing Service®, and the associated logos are owned by the Canadian Real Estate Association (CREA) and identify the quality of services provided by real estate professionals who are members of CREA.</li>
                <li><strong>E. &amp; O.E.</strong> — Errors and omissions excepted.</li>
            </ul>
        </div>

        <!-- ── Invisibility Gap ── -->
        <div class="terms-section" id="d-gap">
            <div class="disc-badge disc-badge-gold">Pre-Sale Listings</div>
            <h2 class="terms-h2">The "Invisibility Gap" — Pre-Sale Data Limitations</h2>

            <p>Wynston specializes in tracking real estate projects during the <strong>"Invisibility Gap"</strong> — the period of approximately 18 to 36 months between a development permit being issued and a project reaching the MLS® and formal pre-sale phases. During this window, projects are real and progressing, but information is necessarily <em>preliminary, estimated, and subject to change</em>.</p>

            <div class="terms-callout terms-callout-warning">
                <strong>Important:</strong> All "Coming Soon" and pre-sale listings on this Platform are based on preliminary public records, development permit applications, and information provided directly by developers. This information has <strong>not been verified by Wynston</strong> and may not reflect final approved plans, rezoning outcomes, or changes made by the developer or municipality.
            </div>

            <p>Specifically, you should be aware that for all Coming Soon and pre-sale listings:</p>
            <ul class="terms-list">
                <li><strong>Estimated completion dates</strong> are based on preliminary development timelines and are subject to change without notice due to construction delays, permit revisions, or developer decisions.</li>
                <li><strong>Unit specifications</strong> (number of bedrooms, square footage, floor plans) are based on preliminary design documents and may differ materially from the final constructed project.</li>
                <li><strong>Pricing indications</strong> (where provided) are approximations only and do not constitute a binding offer or advertisement of a unit for sale under REDMA.</li>
                <li><strong>Renderings and floor plans</strong> are artistic representations. They are not guaranteed to reflect the final appearance or layout of the completed project.</li>
                <li><strong>Project status</strong> (including whether a project will proceed at all) is subject to change. Wynston does not guarantee that any listed project will reach completion.</li>
            </ul>
            <p>All pre-sale purchase decisions should be made only after reviewing a developer's <strong>Disclosure Statement</strong> filed with the BC Financial Services Authority and obtaining independent legal and financial advice.</p>
        </div>

        <!-- ── No Purchase ── -->
        <div class="terms-section" id="d-nopurchase">
            <div class="disc-badge disc-badge-red">Critical Notice</div>
            <h2 class="terms-h2">No Purchase or Deposit Accepted</h2>

            <div class="disc-nopurchase-block">
                <div class="disc-nopurchase-icon">⚠️</div>
                <div>
                    <div class="disc-nopurchase-title">NO PURCHASE CAN BE MADE THROUGH THIS PLATFORM</div>
                    <div class="disc-nopurchase-body">Wynston.ca and the Wynston Mobile Application do not accept deposits, purchase agreements, reservations, expressions of interest, or any other form of commitment to purchase real estate. No money should be sent to Wynston in connection with the purchase of any property.</div>
                </div>
            </div>

            <p style="margin-top:20px;">Any purchase of a pre-sale unit must be completed:</p>
            <ul class="terms-list">
                <li>directly with the developer's authorized sales team;</li>
                <li>pursuant to a signed Purchase Agreement that complies with all requirements of REDMA and the BC Financial Services Authority; and</li>
                <li>only after receiving and reviewing the developer's Disclosure Statement.</li>
            </ul>
            <p>If you have been asked to submit a deposit or payment through this Platform, please contact us immediately at <a href="mailto:info@wynston.ca">info@wynston.ca</a>.</p>
        </div>

        <!-- ── VOW ── -->
        <div class="terms-section" id="d-vow">
            <div class="disc-badge disc-badge-blue">VOW Notice</div>
            <h2 class="terms-h2">VOW Registration Requirement</h2>

            <p>In compliance with the <strong>Real Estate Board of Greater Vancouver's Virtual Office Website (VOW) Rules</strong>, certain data available on this Platform — including sold prices, detailed listing history, and restricted project documents — may require you to register for a Member Account.</p>

            <p>By registering for a Member Account, you acknowledge and agree that:</p>
            <ul class="terms-list">
                <li>you have a <strong>bona fide interest</strong> in the purchase, sale, or lease of real estate in the Greater Vancouver area;</li>
                <li>you will use MLS® data accessed through this Platform <strong>solely for your own personal, non-commercial research purposes</strong>;</li>
                <li>you are entering into a <strong>lawful broker-consumer relationship</strong> with Tam Nguyen for the purposes of accessing VOW data on this website only — this does not constitute a Buyer Representation Agreement or any other representation agreement; and</li>
                <li>you will not copy, redistribute, publish, or commercially exploit any MLS® data obtained through this Platform.</li>
            </ul>
            <p>Violation of these conditions may result in immediate account termination and may expose you to legal liability under the Real Estate Board of Greater Vancouver's Rules and applicable copyright law.</p>
        </div>

        <!-- ── REDMA ── -->
        <div class="terms-section" id="d-redma">
            <div class="disc-badge disc-badge-gold">For Developers</div>
            <h2 class="terms-h2">REDMA Compliance Notice for Developers</h2>

            <p>This notice applies to all developers, builders, and their representatives who list projects on the Wynston Platform.</p>

            <div class="terms-callout terms-callout-navy">
                <strong>Wynston is a marketing platform, not a compliance service.</strong> Wynston does not review Content for compliance with the Real Estate Development Marketing Act (REDMA), SBC 2004, c. 41, or any other applicable law. Developers are solely responsible for ensuring their listings, marketing materials, and sales activities comply with all applicable legislation.
            </div>

            <p>Key REDMA obligations that developers must be aware of include:</p>
            <ul class="terms-list">
                <li><strong>Disclosure Statement:</strong> A Disclosure Statement approved by the BC Financial Services Authority must be filed before any pre-sale units are marketed or sold to the public. The filing of a Disclosure Statement is the developer's sole responsibility.</li>
                <li><strong>Advertising restrictions:</strong> Pre-sale marketing must not misrepresent the project. All pricing indications, completion timelines, and unit specifications must be accurate and clearly qualified as estimates.</li>
                <li><strong>Deposit obligations:</strong> All deposits received from purchasers of pre-sale units must be held in trust in accordance with REDMA requirements.</li>
                <li><strong>Amendment obligations:</strong> Material changes to a project that affect purchasers' rights may trigger a requirement to amend the Disclosure Statement and provide purchasers with a rescission right.</li>
            </ul>
            <p>Developers are strongly encouraged to obtain independent legal advice from a BC real estate lawyer experienced in REDMA compliance before listing any pre-sale project on any platform, including Wynston.</p>
            <p>By submitting a listing to Wynston, the Developer confirms that they have obtained or are in the process of obtaining all required regulatory approvals for their marketing activities.</p>
        </div>

        <!-- ── No Agency ── -->
        <div class="terms-section" id="d-agency">
            <div class="disc-badge disc-badge-blue">Agency Notice</div>
            <h2 class="terms-h2">No Agency Relationship Created</h2>

            <p>Your use of the Wynston Platform — including browsing listings, registering for a Member Account, submitting a "Notify Me" request, or contacting us through any form — does <strong>not</strong> create a real estate agency relationship between you and Tam Nguyen, Royal Pacific Realty Corporation, or any affiliated party.</p>

            <p>A real estate agency relationship is only formally established through:</p>
            <ul class="terms-list">
                <li>a signed, written <strong>Buyer Representation Agreement (BRA)</strong> for buyers; or</li>
                <li>a signed, written <strong>Listing Service Representation Agreement (LSRA)</strong> for sellers and developers.</li>
            </ul>
            <p>Until such an agreement is executed, Tam Nguyen acts as an unrepresented party facilitator only. No fiduciary duties are owed to Platform users unless a representation agreement is in place. If you are uncertain about your representation status, please contact us directly at <a href="mailto:info@wynston.ca">info@wynston.ca</a>.</p>
        </div>

        <!-- ── Professional Disclosure ── -->
        <div class="terms-section" id="d-prof">
            <div class="disc-badge disc-badge-blue">Professional Disclosure</div>
            <h2 class="terms-h2">Professional Disclosure</h2>

            <div class="disc-prof-card">
                <div class="disc-prof-left">
                    <div class="disc-prof-name">Tam Nguyen</div>
                    <div class="disc-prof-title">REALTOR® &amp; Licensed Real Estate Agent</div>
                    <div class="disc-prof-brokerage">Royal Pacific Realty Corporation</div>
                </div>
                <div class="disc-prof-right">
                    <div class="disc-prof-detail"><span>Registration:</span> Real Estate Board of Greater Vancouver</div>
                    <div class="disc-prof-detail"><span>Regulator:</span> BC Financial Services Authority (BCFSA)</div>
                    <div class="disc-prof-detail"><span>Brokerage License:</span> Royal Pacific Realty Corporation</div>
                    <div class="disc-prof-detail"><span>Contact:</span> <a href="mailto:info@wynston.ca">info@wynston.ca</a></div>
                </div>
            </div>

            <p style="margin-top:20px;">All real estate trading activities facilitated through connections made on this Platform are conducted exclusively through Tam Nguyen and Royal Pacific Realty Corporation, in accordance with:</p>
            <ul class="terms-list">
                <li>The <em>Real Estate Services Act</em>, RSBC 1996, c. 397;</li>
                <li>The regulations and bylaws of the British Columbia Financial Services Authority (BCFSA);</li>
                <li>The Real Estate Board of Greater Vancouver Rules and Regulations; and</li>
                <li>The <em>Real Estate Development Marketing Act (REDMA)</em>, SBC 2004, c. 41.</li>
            </ul>
            <p>Wynston.ca is not affiliated with or endorsed by the Real Estate Board of Greater Vancouver, the BCFSA, CREA, or any government authority.</p>

            <div class="disc-legal-links">
                <span>For full details, see our legal documents:</span>
                <a href="terms.php">Terms of Service</a>
                <a href="privacy.php">Privacy Policy</a>
            </div>
        </div>

    </div><!-- /terms-body -->
    </div><!-- /col-lg-9 -->

</div><!-- /row -->
</div><!-- /container -->
</section>
<!-- ============================ Disclaimer Body End ================================== -->


<style>
section { padding: 60px 0; }

/* ── Shared TOC (same as terms/privacy) ───────────────────────────── */
.terms-toc {
    position: sticky; top: 90px; background: #fff;
    border: 1px solid #e8e4dd; border-radius: 12px;
    padding: 24px 20px; margin-top: 40px;
    box-shadow: 0 2px 16px rgba(0,36,70,.06);
}
.terms-toc-title { font-size:11px; font-weight:800; text-transform:uppercase; letter-spacing:1.2px; color:#c9a84c; margin-bottom:14px; padding-bottom:10px; border-bottom:2px solid #f0ece6; }
.terms-toc-list { list-style:none; padding:0; margin:0; }
.terms-toc-list li { margin-bottom:2px; }
.terms-toc-list a { display:block; font-size:12px; font-weight:600; color:#555; text-decoration:none; padding:5px 8px; border-radius:6px; transition:background .15s,color .15s; line-height:1.4; }
.terms-toc-list a:hover, .terms-toc-list a.active { background:#f0f4ff; color:#002446; }

.terms-body { padding: 40px 0 40px 40px; }
.terms-preamble { background:#f0f4ff; border-left:4px solid #002446; border-radius:0 8px 8px 0; padding:18px 20px; font-size:13px; color:#002446; line-height:1.7; margin-bottom:40px; }
.terms-section { margin-bottom:48px; padding-bottom:48px; border-bottom:1px solid #f0ece6; }
.terms-section:last-of-type { border-bottom:none; }
.terms-section p { font-size:14px; color:#555; line-height:1.85; margin-bottom:14px; }
.terms-h2 { font-size:20px; font-weight:800; color:#002446; margin-bottom:18px; padding-bottom:12px; border-bottom:2px solid #c9a84c; display:inline-block; }
.terms-list { padding-left:20px; margin-bottom:14px; }
.terms-list li { font-size:14px; color:#555; line-height:1.85; margin-bottom:6px; padding-left:4px; }
.terms-list li::marker { color:#c9a84c; }
.terms-callout { border-radius:8px; padding:18px 20px; font-size:13px; line-height:1.7; margin:20px 0; }
.terms-callout-warning { background:#fffbeb; border-left:4px solid #c9a84c; color:#7c5a00; }
.terms-callout-navy    { background:#f0f4ff; border-left:4px solid #002446; color:#002446; }

/* ── Section badges ────────────────────────────────────────────────── */
.disc-badge {
    display: inline-block; font-size:10px; font-weight:800;
    text-transform:uppercase; letter-spacing:1px;
    padding:4px 12px; border-radius:20px; margin-bottom:12px;
}
.disc-badge-blue { background:#e8f0ff; color:#002446; }
.disc-badge-gold { background:#fef3d0; color:#7c5a00; }
.disc-badge-red  { background:#fff0f0; color:#a00000; }

/* ── REBGV attribution block ───────────────────────────────────────── */
.disc-rebgv-block {
    display:flex; gap:20px; align-items:flex-start;
    background:#f8faff; border:1px solid #dde4f0;
    border-radius:10px; padding:20px; margin-bottom:8px;
}
.disc-rebgv-logo-area { flex-shrink:0; }
.disc-rebgv-seal {
    width:60px; height:60px; border-radius:50%;
    background:#002446; color:#c9a84c;
    display:flex; align-items:center; justify-content:center;
    font-size:13px; font-weight:900; letter-spacing:1px;
    border:3px solid #c9a84c;
}
.disc-rebgv-text { font-size:12px; color:#555; line-height:1.8; font-style:italic; }

/* ── No purchase block ─────────────────────────────────────────────── */
.disc-nopurchase-block {
    display:flex; gap:16px; align-items:flex-start;
    background:#fff5f5; border:2px solid #e53e3e;
    border-radius:10px; padding:20px;
}
.disc-nopurchase-icon { font-size:32px; flex-shrink:0; margin-top:2px; }
.disc-nopurchase-title { font-size:14px; font-weight:900; color:#a00000; text-transform:uppercase; letter-spacing:.5px; margin-bottom:8px; }
.disc-nopurchase-body  { font-size:13px; color:#555; line-height:1.7; }

/* ── Professional card ─────────────────────────────────────────────── */
.disc-prof-card {
    display:flex; gap:0; border:1px solid #e8e4dd;
    border-radius:12px; overflow:hidden; margin-bottom:8px;
}
.disc-prof-left {
    background:#002446; color:#fff; padding:24px 28px;
    flex:0 0 220px; display:flex; flex-direction:column; gap:6px;
}
.disc-prof-name { font-size:18px; font-weight:800; color:#fff; }
.disc-prof-title { font-size:12px; color:#c9a84c; font-weight:700; }
.disc-prof-brokerage { font-size:11px; color:rgba(255,255,255,.6); margin-top:4px; }
.disc-prof-right {
    background:#f8faff; padding:20px 24px; flex:1;
    display:flex; flex-direction:column; justify-content:center; gap:8px;
}
.disc-prof-detail { font-size:13px; color:#555; }
.disc-prof-detail span { font-weight:700; color:#002446; margin-right:6px; }
.disc-prof-detail a { color:#0065ff; text-decoration:none; }
.disc-prof-detail a:hover { text-decoration:underline; }

/* ── Footer legal links ────────────────────────────────────────────── */
.disc-legal-links {
    display:flex; align-items:center; gap:12px; flex-wrap:wrap;
    background:#002446; border-radius:8px; padding:14px 18px;
    margin-top:20px;
}
.disc-legal-links span { font-size:12px; color:rgba(255,255,255,.6); }
.disc-legal-links a {
    font-size:12px; font-weight:700; color:#c9a84c;
    text-decoration:none; padding:4px 12px;
    border:1px solid rgba(201,168,76,.4); border-radius:20px;
    transition:background .15s;
}
.disc-legal-links a:hover { background:rgba(201,168,76,.15); }

/* ── Mobile ────────────────────────────────────────────────────────── */
@media (max-width:991px) { .terms-body { padding:24px 0; } }
@media (max-width:767px) {
    .disc-prof-card { flex-direction:column; }
    .disc-prof-left { flex:none; }
    .disc-rebgv-block { flex-direction:column; }
}
</style>

<script>
(function() {
    var sections = document.querySelectorAll('.terms-section[id]');
    var links    = document.querySelectorAll('.terms-toc-list a[href^="#"]');
    if (!sections.length || !links.length) return;
    function onScroll() {
        var scrollY = window.scrollY + 120;
        var current = '';
        sections.forEach(function(s) { if (s.offsetTop <= scrollY) current = s.id; });
        links.forEach(function(a) { a.classList.toggle('active', a.getAttribute('href') === '#' + current); });
    }
    window.addEventListener('scroll', onScroll, { passive: true });
    onScroll();
})();
</script>

<?php
$hero_content = ob_get_clean();
include "$base_dir/style/base.php";
?>